# Generated by Django 2.1.7 on 2020-06-09 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('eng_name', models.CharField(max_length=64)),
                ('han_name', models.CharField(max_length=16)),
                ('gender', models.CharField(blank=True, max_length=1, null=True)),
                ('age', models.CharField(blank=True, max_length=5, null=True)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Menus',
            fields=[
                ('menu_id', models.AutoField(primary_key=True, serialize=False)),
                ('menu_name', models.CharField(max_length=30)),
                ('menu_price', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('sales_id', models.AutoField(primary_key=True, serialize=False)),
                ('regdate', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Customers')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Menus')),
            ],
        ),
    ]
