# Generated by Django 2.1.7 on 2020-06-09 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='regdate',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
