# Generated by Django 2.1.7 on 2020-06-10 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('face', '0002_auto_20200609_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='Historypoints',
            fields=[
                ('points_id', models.AutoField(primary_key=True, serialize=False)),
                ('cur_point', models.IntegerField(default=0)),
                ('sum_point', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Point',
            fields=[
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='face.Customers')),
                ('point', models.IntegerField(default=0)),
            ],
        ),
        migrations.AddField(
            model_name='historypoints',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='face.Customers'),
        ),
    ]
